- name: variables from files
  hosts: localhost #managing the ansible server itself
  vars_files:
   - variables.yaml
  tasks:
   - name: print the variables
     ansible.builtin.debug:
      msg: " we are learning {{COURSE}},duration is {{DURATION}} tranining is {{TRANING}}"
