- name: variables from files
  hosts: local host #managing the ansible server itself
  vars_files:
  tasks:
   - name: print the variables
     ansible.builtin.debug:
      msg: " we are learning {{COURSE}},duration is {{DURATION}} tranining is {{TRANING}}"
